#script to generate html files with references automatically


DOC := publications
REFS := references.bib
REFS_DOC := refs
REFS_DOC_NO_LINKS := refs_nl
REFS_DOC_OA := refs_only_abstract
TAR_FILE := refs.tar.gz


$(DOC).aux: $(DOC).tex $(REFS)
	latex $(DOC).tex
	bibtex $(DOC).aux
	latex $(DOC).tex

$(REFS_DOC).bib: $(DOC).aux
	#aux2bib $(DOC).aux > $(REFS_DOC).bib
	bib2bib -ob $(REFS_DOC).bib $(REFS) --remove 'url' --remove 'pdf' --remove 'slides'

$(REFS_DOC_NO_LINKS).bib: $(REFS_DOC).bib
	bib2bib -ob $(REFS_DOC_NO_LINKS).bib $(REFS_DOC).bib --remove 'pdf' --remove 'slides' --remove 'abstract' --remove 'keywords' 

$(REFS_DOC_OA): $(REFS_DOC).bib
	bib2bib -ob $(REFS_DOC_OA).bib $(REFS_DOC).bib --remove 'pdf' --remove 'slides' --remove 'keywords' 
	bibtex2html --both --no-keywords -nodoc -nf 'slides' 'slides' $(REFS_DOC_OA).bib

$(REFS_DOC).html: $(REFS_DOC_NO_LINKS).bib $(REFS_DOC).bib 
	bibtex2html --no-keywords -nodoc -nf 'slides' 'slides' $(REFS_DOC_NO_LINKS).bib
	#rm $(REFS_DOC_NO_LINKS).html
	cp $(REFS_DOC_NO_LINKS)_bib.html $(REFS_DOC)_bib.html.tmp
	bibtex2html --both --no-keywords -nodoc -nf 'slides' 'slides' $(REFS_DOC).bib
	#bibtex2html --no-keywords --no-abstract -nodoc -nf 'slides' 'slides' $(REFS_DOC).bib
	rm $(REFS_DOC)_bib.html
	mv  $(REFS_DOC)_bib.html.tmp $(REFS_DOC)_bib.html
	rm $(REFS_DOC_NO_LINKS).bib

$(TAR_FILE): $(REFS_DOC).html
	tar -cvf  $(TAR_FILE) $(REFS_DOC).html $(REFS_DOC)_bib.html $(REFS_DOC)_abstracts.html ./docs

all: $(REFS_DOC).html $(REFS_DOC_OA)
	#cp $(REFS_DOC).html $(REFS_DOC)_bib.html $(REFS_DOC)_abstracts.html ../public_html/



clean:
	rm -f $(DOC).aux refs.bib refs_only_abstract.bib *.html *.log *.bbl *.dvi *.blg *.pdf *.synctex.gz $(REFS_DOC_NO_LINKS).bib $(REFS_DOC).bib $(TAR_FILE)



